name: Build and Test iOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v3

    - name: List repository contents
      run: ls -R .
    
    - name: Check project file
      run: |
        ls -l AmorPorFilmesSeries.xcodeproj
        if [ ! -s AmorPorFilmesSeries.xcodeproj ]; then
          echo "Error: Project file is empty or does not exist."
          exit 1
        fi

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_15.4.app

    - name: Xcode version
      run: xcodebuild -version

    - name: Build
      run: xcodebuild clean build -project AmorPorFilmesSeries.xcodeproj -scheme AmorPorFilmesSeries -sdk iphoneos CODE_SIGNING_ALLOWED=NO
